export type TeamCountryMeta = {
    name: string;
    rgb: string;
    flagEmoji: string;
};

export const teamCountryMeta: Record<string, TeamCountryMeta> = {
    MEX: { name: "Mexico", rgb: "rgb(0, 104, 71)", flagEmoji: "🇲🇽" },
    RSA: { name: "Africa do Sul", rgb: "rgb(0, 122, 77)", flagEmoji: "🇿🇦" },
    KOR: { name: "Coreia do Sul", rgb: "rgb(196, 30, 58)", flagEmoji: "🇰🇷" },
    CZE: { name: "Republica Tcheca", rgb: "rgb(17, 69, 126)", flagEmoji: "🇨🇿" },
    CAN: { name: "Canada", rgb: "rgb(198, 12, 48)", flagEmoji: "🇨🇦" },
    BIH: { name: "Bosnia e Herzegovina", rgb: "rgb(0, 56, 147)", flagEmoji: "🇧🇦" },
    QAT: { name: "Catar", rgb: "rgb(126, 0, 52)", flagEmoji: "🇶🇦" },
    SUI: { name: "Suica", rgb: "rgb(218, 41, 28)", flagEmoji: "🇨🇭" },
    BRA: { name: "Brasil", rgb: "rgb(0, 133, 72)", flagEmoji: "🇧🇷" },
    MAR: { name: "Marrocos", rgb: "rgb(184, 28, 48)", flagEmoji: "🇲🇦" },
    HAI: { name: "Haiti", rgb: "rgb(0, 45, 114)", flagEmoji: "🇭🇹" },
    SCO: { name: "Escocia", rgb: "rgb(0, 82, 147)", flagEmoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
    USA: { name: "Estados Unidos", rgb: "rgb(60, 59, 110)", flagEmoji: "🇺🇸" },
    PAR: { name: "Paraguai", rgb: "rgb(186, 31, 58)", flagEmoji: "🇵🇾" },
    AUS: { name: "Australia", rgb: "rgb(1, 33, 105)", flagEmoji: "🇦🇺" },
    TUR: { name: "Turquia", rgb: "rgb(196, 16, 46)", flagEmoji: "🇹🇷" },
    GER: { name: "Alemanha", rgb: "rgb(32, 32, 32)", flagEmoji: "🇩🇪" },
    CUW: { name: "Curacao", rgb: "rgb(0, 80, 157)", flagEmoji: "🇨🇼" },
    CIV: { name: "Costa do Marfim", rgb: "rgb(209, 108, 0)", flagEmoji: "🇨🇮" },
    ECU: { name: "Equador", rgb: "rgb(0, 57, 166)", flagEmoji: "🇪🇨" },
    NED: { name: "Paises Baixos", rgb: "rgb(174, 28, 40)", flagEmoji: "🇳🇱" },
    JPN: { name: "Japao", rgb: "rgb(188, 0, 45)", flagEmoji: "🇯🇵" },
    SWE: { name: "Suecia", rgb: "rgb(0, 82, 147)", flagEmoji: "🇸🇪" },
    TUN: { name: "Tunisia", rgb: "rgb(210, 16, 52)", flagEmoji: "🇹🇳" },
    BEL: { name: "Belgica", rgb: "rgb(32, 32, 32)", flagEmoji: "🇧🇪" },
    EGY: { name: "Egito", rgb: "rgb(206, 17, 38)", flagEmoji: "🇪🇬" },
    IRN: { name: "Ira", rgb: "rgb(0, 122, 61)", flagEmoji: "🇮🇷" },
    NZL: { name: "Nova Zelandia", rgb: "rgb(0, 45, 114)", flagEmoji: "🇳🇿" },
    ESP: { name: "Espanha", rgb: "rgb(170, 21, 27)", flagEmoji: "🇪🇸" },
    CPV: { name: "Cabo Verde", rgb: "rgb(0, 57, 166)", flagEmoji: "🇨🇻" },
    KSA: { name: "Arabia Saudita", rgb: "rgb(0, 108, 53)", flagEmoji: "🇸🇦" },
    URU: { name: "Uruguai", rgb: "rgb(0, 56, 168)", flagEmoji: "🇺🇾" },
    FRA: { name: "Franca", rgb: "rgb(0, 85, 164)", flagEmoji: "🇫🇷" },
    SEN: { name: "Senegal", rgb: "rgb(0, 133, 63)", flagEmoji: "🇸🇳" },
    IRQ: { name: "Iraque", rgb: "rgb(206, 17, 38)", flagEmoji: "🇮🇶" },
    NOR: { name: "Noruega", rgb: "rgb(186, 12, 47)", flagEmoji: "🇳🇴" },
    ARG: { name: "Argentina", rgb: "rgb(58, 127, 196)", flagEmoji: "🇦🇷" },
    ALG: { name: "Argelia", rgb: "rgb(0, 122, 61)", flagEmoji: "🇩🇿" },
    AUT: { name: "Austria", rgb: "rgb(200, 16, 46)", flagEmoji: "🇦🇹" },
    JOR: { name: "Jordania", rgb: "rgb(0, 0, 0)", flagEmoji: "🇯🇴" },
    POR: { name: "Portugal", rgb: "rgb(0, 102, 0)", flagEmoji: "🇵🇹" },
    COD: { name: "Congo RD", rgb: "rgb(0, 149, 218)", flagEmoji: "🇨🇩" },
    UZB: { name: "Uzbequistao", rgb: "rgb(0, 133, 190)", flagEmoji: "🇺🇿" },
    COL: { name: "Colombia", rgb: "rgb(0, 57, 166)", flagEmoji: "🇨🇴" },
    ENG: { name: "Inglaterra", rgb: "rgb(200, 16, 46)", flagEmoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
    CRO: { name: "Croacia", rgb: "rgb(0, 56, 147)", flagEmoji: "🇭🇷" },
    GHA: { name: "Gana", rgb: "rgb(0, 122, 61)", flagEmoji: "🇬🇭" },
    PAN: { name: "Panama", rgb: "rgb(0, 57, 166)", flagEmoji: "🇵🇦" },
};
